# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "WasThreadStackProcessor"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alberto Paz"]
  s.date = "2012-05-23"
  s.description = "This utility extracts all the Thread Stacks from a set of thread dump files of a WebSphere Application Server and generates a unique tree with all the threads"
  s.email = "alberto.pazjimenez@gmail.com"
  s.executables = ["WasThreadStackProcessor"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "WasThreadStackProcessor.gemspec",
    "autotest/discover.rb",
    "bin/WasThreadStackProcessor",
    "lib/WasThreadStackProcessor.rb",
    "lib/threadStack.rb",
    "lib/threadStackCombinator.rb",
    "lib/threadStackExtractor.rb",
    "spec/WasThreadStackProcessor_spec.rb",
    "spec/spec_helper.rb",
    "spec/threadStackCombinator_spec.rb",
    "spec/threadStackExtractor_spec.rb",
    "spec/threadStack_spec.rb"
  ]
  s.homepage = "http://github.com/japaz/WasThreadStackProcessor"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Utility to process Thread Stacks from a WebSphere Application Server"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<hirb>, ["~> 0.6.2"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<hirb>, ["~> 0.6.2"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.10.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<hirb>, ["~> 0.6.2"])
  end
end

